logging:
  level:
    root: INFO
    az.task.management: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_manager
    username: fati
    password: fatipassword
  liquibase:
      change-log: classpath:liquibase/changelog-master.xml
#  datasource:
#    driver-class-name: org.hsqldb.jdbc.JDBCDriver
#    url: jdbc:hsqldb:mem:task-management
#    username:
#    password:
#  liquibase:
#    change-log: classpath:liquibase/changelog-master.xml

